---
title: "Final Project Random Forest"
output: html_document
date: "2024-04-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(RCurl)

#importing data from repo
url1 = getURL("https://raw.githubusercontent.com/shoun-lo/asrm-432-fp/main/train.txt")
train_data = read_delim(url1, delim = "\t", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)

url2 = getURL("https://raw.githubusercontent.com/shoun-lo/asrm-432-fp/main/predicts.txt")
predict_data = read_delim(url2, delim = "\t", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)

url3 = getURL("https://raw.githubusercontent.com/shoun-lo/asrm-432-fp/main/targets.txt")
target_data = read_delim(url3, delim = "\t", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)

```

```{r}
set.seed(7)
library(e1071)
naivebayes_train <- naiveBayes(train_data$X86 ~ ., data = train_data, )

naivebayes_train_fitted <- predict(naivebayes_train, newdata = train_data, type = "class")

table(naivebayes_train_fitted, train_data$X86)
```
```{r}
insample_accuracy <- (table(naivebayes_train_fitted, train_data$X86)[1,1] + table(naivebayes_train_fitted, train_data$X86)[2,2]) / dim(train_data)[1]
print(insample_accuracy)
```
```{r}
naivebayes_train
```

```{r}
library(caret)
library(e1071)
ctrl <- trainControl(method = "cv", number = 5)
nb_model <- train(train_data$X86 ~ ., data = train_data, method = "nb", trControl = ctrl)
```


